stages:
#  - build
  - deploy-dev
  
variables: 
  VERSION: 0.0.40
    
build-app:
  stage: build
  image: docker:20-dind
  retry: 2
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: [ "--tls=false" ]
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE/red/red-frontend:$VERSION .
    - docker push $CI_REGISTRY_IMAGE/red/red-frontend:$VERSION

deploy-dev-app:
  stage: deploy-dev
  image: kroniak/ssh-client
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEV_USER}@${DEV_HOST} 
      "cd ./docker_services/red_schedule;
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY;
      export "FRONTEND_VERSION=${VERSION}"; 
      /bin/bash -s " < deploy.sh